branches:
  only:
    - master
    - gh-pages

language: julia

os:
  - linux
  
env:
  - TRAVIS_BUILD_DIR="~/CurricularAnalytics.jl"

julia:
  - nightly
  - 1.0

jobs: 
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        cd $TRAVIS_BUILD_DIR
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
