branches:
  only:
    - master
    - gh-pages

language: julia

os:
  - linux

julia:
  - nightly
  - 1.0

script:
  - pwd
  - cd /home/travis/build/heileman/CurricularAnalytics.jl

jobs: 
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - pwd
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
